### ISSUE TITLE
Is fixture use in the test?

### ISSUE THREAD

**Issue by CubeVic** [Erick-hub/poetrydb-api-testing#1]
There is a fixture on the [`conftest.py`](https://github.com/Erick-hub/poetrydb-api-testing/blob/9d3344144fc4741b125883eb3c52ff217f081d64/tests/conftest.py#L9) but it doesn't seem to be used in the [`test_poem`](https://github.com/Erick-hub/poetrydb-api-testing/blob/9d3344144fc4741b125883eb3c52ff217f081d64/tests/test_poems.py#L5)

```
@pytest.fixture
def get_sample(request):
    _sample = json.loads(f, object_hook=lambda d: SimpleNamespace(**d))
    request.cls_sample = _sample
    return request.cls_sample
```

It might be an initial approach that later was discarded and maybe the code was left behind,
Or maybe I don't understand the initial intention, just in case will be a good idea to double check

**Comment by Erick-hub** [comment]
> There is a fixture on the [`conftest.py`](https://github.com/Erick-hub/poetrydb-api-testing/blob/9d3344144fc4741b125883eb3c52ff217f081d64/tests/conftest.py#L9) but it doesn't seem to be used in the [`test_poem`](https://github.com/Erick-hub/poetrydb-api-testing/blob/9d3344144fc4741b125883eb3c52ff217f081d64/tests/test_poems.py#L5)
> 
> ```
> @pytest.fixture
> def get_sample(request):
>     _sample = json.loads(f, object_hook=lambda d: SimpleNamespace(**d))
>     request.cls_sample = _sample
>     return request.cls_sample
> ```
> 
> It might be an initial approach that later was discarded and maybe the code was left behind, Or maybe I don't understand the initial intention, just in case will be a good idea to double check

Hey Victor, 

Yes that is correct, the fixture isn't used in the test. My initial approach was using the fixture at the class level for BaseTest and pass the sample poem as a class attribute to later be used in the tests. I ran into some troubles trying to implement this approach and decided to put in the backburner. As of now the Test object does not inherit the BaseTest fixtures.

**Comment by Erick-hub** [comment]
implemented fixture on class level for BaseTest
